In [4]:
print("hello")
x = 4

hello


In [5]:
print(x)

4


In [6]:
# this is a comment


None of this is going to be compiled
Hooray

In [11]:
#functions
def foo(x):
    return x*2

foo(400)
foo(200)
foo(100)

200

In [10]:
# if statement
y = 12
if y < 10:
    print("garbage")
elif y > 12:
    print("even more garbage")
else:
    print("wheeeeeee")

wheeeeeee


In [16]:
#Exercise 1 - create a function that takes in 3 parameters: a b c. If a is
#a 0, return b+c, if a is a 1, return b-c, if a is neither, return b * c
def bunchofmath(a, b, c):
    if a == 0:
        return b + c
    elif a == 1:
        return b - c
    else:
        return b * c

print(bunchofmath(0, 4, 5))
print(bunchofmath(2, 4, 5))

9
20


In [17]:
#loop
a = ['cat', 'dog', 'Fred']
for x in a:
    print(x)


cat
dog
Fred


In [18]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [19]:
true


NameError: name 'true' is not defined

In [20]:
True

True

In [21]:
False

False

In [22]:
range(1, 10)

range(1, 10)

In [23]:
for i in range(1, 10):
    print(i)

1
2
3
4
5
6
7
8
9


In [27]:
for i in range(10, 0, -2):
    print(i)
    

10
8
6
4
2


In [33]:
x = 10
while x < 5000:
    print("Wheeeeeeee " + str(x) + "\n")
    x = x + 1

Wheeeeeeee 10

Wheeeeeeee 11

Wheeeeeeee 12

Wheeeeeeee 13

Wheeeeeeee 14

Wheeeeeeee 15

Wheeeeeeee 16

Wheeeeeeee 17

Wheeeeeeee 18

Wheeeeeeee 19

Wheeeeeeee 20

Wheeeeeeee 21

Wheeeeeeee 22

Wheeeeeeee 23

Wheeeeeeee 24

Wheeeeeeee 25

Wheeeeeeee 26

Wheeeeeeee 27

Wheeeeeeee 28

Wheeeeeeee 29

Wheeeeeeee 30

Wheeeeeeee 31

Wheeeeeeee 32

Wheeeeeeee 33

Wheeeeeeee 34

Wheeeeeeee 35

Wheeeeeeee 36

Wheeeeeeee 37

Wheeeeeeee 38

Wheeeeeeee 39

Wheeeeeeee 40

Wheeeeeeee 41

Wheeeeeeee 42

Wheeeeeeee 43

Wheeeeeeee 44

Wheeeeeeee 45

Wheeeeeeee 46

Wheeeeeeee 47

Wheeeeeeee 48

Wheeeeeeee 49

Wheeeeeeee 50

Wheeeeeeee 51

Wheeeeeeee 52

Wheeeeeeee 53

Wheeeeeeee 54

Wheeeeeeee 55

Wheeeeeeee 56

Wheeeeeeee 57

Wheeeeeeee 58

Wheeeeeeee 59

Wheeeeeeee 60

Wheeeeeeee 61

Wheeeeeeee 62

Wheeeeeeee 63

Wheeeeeeee 64

Wheeeeeeee 65

Wheeeeeeee 66

Wheeeeeeee 67

Wheeeeeeee 68

Wheeeeeeee 69

Wheeeeeeee 70

Wheeeeeeee 71

Wheeeeeeee 72

Wheeeeeeee 73

Wheeeeeeee 74

Wheeeeeeee 75

Wheeeeeeee

Wheeeeeeee 1481

Wheeeeeeee 1482

Wheeeeeeee 1483

Wheeeeeeee 1484

Wheeeeeeee 1485

Wheeeeeeee 1486

Wheeeeeeee 1487

Wheeeeeeee 1488

Wheeeeeeee 1489

Wheeeeeeee 1490

Wheeeeeeee 1491

Wheeeeeeee 1492

Wheeeeeeee 1493

Wheeeeeeee 1494

Wheeeeeeee 1495

Wheeeeeeee 1496

Wheeeeeeee 1497

Wheeeeeeee 1498

Wheeeeeeee 1499

Wheeeeeeee 1500

Wheeeeeeee 1501

Wheeeeeeee 1502

Wheeeeeeee 1503

Wheeeeeeee 1504

Wheeeeeeee 1505

Wheeeeeeee 1506

Wheeeeeeee 1507

Wheeeeeeee 1508

Wheeeeeeee 1509

Wheeeeeeee 1510

Wheeeeeeee 1511

Wheeeeeeee 1512

Wheeeeeeee 1513

Wheeeeeeee 1514

Wheeeeeeee 1515

Wheeeeeeee 1516

Wheeeeeeee 1517

Wheeeeeeee 1518

Wheeeeeeee 1519

Wheeeeeeee 1520

Wheeeeeeee 1521

Wheeeeeeee 1522

Wheeeeeeee 1523

Wheeeeeeee 1524

Wheeeeeeee 1525

Wheeeeeeee 1526

Wheeeeeeee 1527

Wheeeeeeee 1528

Wheeeeeeee 1529

Wheeeeeeee 1530

Wheeeeeeee 1531

Wheeeeeeee 1532

Wheeeeeeee 1533

Wheeeeeeee 1534

Wheeeeeeee 1535

Wheeeeeeee 1536

Wheeeeeeee 1537

Wheeeeeeee 1538

Wheeeeeeee 153


Wheeeeeeee 2481

Wheeeeeeee 2482

Wheeeeeeee 2483

Wheeeeeeee 2484

Wheeeeeeee 2485

Wheeeeeeee 2486

Wheeeeeeee 2487

Wheeeeeeee 2488

Wheeeeeeee 2489

Wheeeeeeee 2490

Wheeeeeeee 2491

Wheeeeeeee 2492

Wheeeeeeee 2493

Wheeeeeeee 2494

Wheeeeeeee 2495

Wheeeeeeee 2496

Wheeeeeeee 2497

Wheeeeeeee 2498

Wheeeeeeee 2499

Wheeeeeeee 2500

Wheeeeeeee 2501

Wheeeeeeee 2502

Wheeeeeeee 2503

Wheeeeeeee 2504

Wheeeeeeee 2505

Wheeeeeeee 2506

Wheeeeeeee 2507

Wheeeeeeee 2508

Wheeeeeeee 2509

Wheeeeeeee 2510

Wheeeeeeee 2511

Wheeeeeeee 2512

Wheeeeeeee 2513

Wheeeeeeee 2514

Wheeeeeeee 2515

Wheeeeeeee 2516

Wheeeeeeee 2517

Wheeeeeeee 2518

Wheeeeeeee 2519

Wheeeeeeee 2520

Wheeeeeeee 2521

Wheeeeeeee 2522

Wheeeeeeee 2523

Wheeeeeeee 2524

Wheeeeeeee 2525

Wheeeeeeee 2526

Wheeeeeeee 2527

Wheeeeeeee 2528

Wheeeeeeee 2529

Wheeeeeeee 2530

Wheeeeeeee 2531

Wheeeeeeee 2532

Wheeeeeeee 2533

Wheeeeeeee 2534

Wheeeeeeee 2535

Wheeeeeeee 2536

Wheeeeeeee 2537

Wheeeeeeee 2538

Wheeeeeeee 25

Wheeeeeeee 3480

Wheeeeeeee 3481

Wheeeeeeee 3482

Wheeeeeeee 3483

Wheeeeeeee 3484

Wheeeeeeee 3485

Wheeeeeeee 3486

Wheeeeeeee 3487

Wheeeeeeee 3488

Wheeeeeeee 3489

Wheeeeeeee 3490

Wheeeeeeee 3491

Wheeeeeeee 3492

Wheeeeeeee 3493

Wheeeeeeee 3494

Wheeeeeeee 3495

Wheeeeeeee 3496

Wheeeeeeee 3497

Wheeeeeeee 3498

Wheeeeeeee 3499

Wheeeeeeee 3500

Wheeeeeeee 3501

Wheeeeeeee 3502

Wheeeeeeee 3503

Wheeeeeeee 3504

Wheeeeeeee 3505

Wheeeeeeee 3506

Wheeeeeeee 3507

Wheeeeeeee 3508

Wheeeeeeee 3509

Wheeeeeeee 3510

Wheeeeeeee 3511

Wheeeeeeee 3512

Wheeeeeeee 3513

Wheeeeeeee 3514

Wheeeeeeee 3515

Wheeeeeeee 3516

Wheeeeeeee 3517

Wheeeeeeee 3518

Wheeeeeeee 3519

Wheeeeeeee 3520

Wheeeeeeee 3521

Wheeeeeeee 3522

Wheeeeeeee 3523

Wheeeeeeee 3524

Wheeeeeeee 3525

Wheeeeeeee 3526

Wheeeeeeee 3527

Wheeeeeeee 3528

Wheeeeeeee 3529

Wheeeeeeee 3530

Wheeeeeeee 3531

Wheeeeeeee 3532

Wheeeeeeee 3533

Wheeeeeeee 3534

Wheeeeeeee 3535

Wheeeeeeee 3536

Wheeeeeeee 3537

Wheeeeeeee 353


Wheeeeeeee 4480

Wheeeeeeee 4481

Wheeeeeeee 4482

Wheeeeeeee 4483

Wheeeeeeee 4484

Wheeeeeeee 4485

Wheeeeeeee 4486

Wheeeeeeee 4487

Wheeeeeeee 4488

Wheeeeeeee 4489

Wheeeeeeee 4490

Wheeeeeeee 4491

Wheeeeeeee 4492

Wheeeeeeee 4493

Wheeeeeeee 4494

Wheeeeeeee 4495

Wheeeeeeee 4496

Wheeeeeeee 4497

Wheeeeeeee 4498

Wheeeeeeee 4499

Wheeeeeeee 4500

Wheeeeeeee 4501

Wheeeeeeee 4502

Wheeeeeeee 4503

Wheeeeeeee 4504

Wheeeeeeee 4505

Wheeeeeeee 4506

Wheeeeeeee 4507

Wheeeeeeee 4508

Wheeeeeeee 4509

Wheeeeeeee 4510

Wheeeeeeee 4511

Wheeeeeeee 4512

Wheeeeeeee 4513

Wheeeeeeee 4514

Wheeeeeeee 4515

Wheeeeeeee 4516

Wheeeeeeee 4517

Wheeeeeeee 4518

Wheeeeeeee 4519

Wheeeeeeee 4520

Wheeeeeeee 4521

Wheeeeeeee 4522

Wheeeeeeee 4523

Wheeeeeeee 4524

Wheeeeeeee 4525

Wheeeeeeee 4526

Wheeeeeeee 4527

Wheeeeeeee 4528

Wheeeeeeee 4529

Wheeeeeeee 4530

Wheeeeeeee 4531

Wheeeeeeee 4532

Wheeeeeeee 4533

Wheeeeeeee 4534

Wheeeeeeee 4535

Wheeeeeeee 4536

Wheeeeeeee 4537

Wheeeeeeee 45

In [29]:
i = input("Give me a numbah!")

Give me a numbah!42


In [30]:
print(i)

42


In [38]:
# Exercise 2 - create a function called facts that passes a
# single parameter x and computes the factorial of x and returns it
# Then ask the user for input, get a number, then call facts(x) and print
# the result.

def facts(x):
    y = x
    for j in range(1, x):
        x = x * (y-j)
    return x

print(facts(int(input("Enter a number: "))))

Enter a number: 5
120


In [39]:
import numpy as np

In [40]:
a = np.arrange(15).reshape(3, 5)


AttributeError: module 'numpy' has no attribute 'arrange'

In [41]:
a = np.arange(15).reshape(3, 5)

In [42]:
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [43]:
a.dim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

In [44]:
a.ndim

2

In [45]:
a.shape

(3, 5)

In [46]:
a.size

15

In [47]:
a = [1, 2, 3]

In [48]:
b = ["string", 0.1, True]

In [49]:
c = [a, b, []]

In [50]:
print(c)

[[1, 2, 3], ['string', 0.1, True], []]


In [51]:
a[0]

1

In [52]:
a[3]

IndexError: list index out of range

In [53]:
a[0] = 12
print(a)

[12, 2, 3]


In [54]:
a

[12, 2, 3]

In [55]:
c

[[12, 2, 3], ['string', 0.1, True], []]

In [56]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [57]:
x[:3]

[0, 1, 2]

In [58]:
x[3:]

[3, 4, 5, 6, 7, 8, 9]

In [59]:
x[1:5]

[1, 2, 3, 4]

In [60]:
x[-3:]

[7, 8, 9]

In [61]:
x[:]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [62]:
x.extend(a)

In [63]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12, 2, 3]

In [64]:
x = [4, 5, 6]

In [65]:
x = x + a

In [66]:
x

[4, 5, 6, 12, 2, 3]

In [67]:
x.append(7)

In [68]:
x

[4, 5, 6, 12, 2, 3, 7]

In [69]:
4 in x

True

In [70]:
1 in x

False

In [74]:
# exercise 3 - create a function that passes in two variables x and y, and 
# returns a list of x random integers from 0 to y, inclusive.
import random

def randList(x, y):
    a = []
    for i in range(x):
        a.append(random.randint(0, y))
    return a

print(randList(5, 10))

[5, 6, 8, 4, 5]


In [76]:
#tuples example
def sum_and_product(x, y):
    return (x+y), (x*y)

sum_and_product(3, 4)


(7, 12)

In [77]:
grades = {"Joel" : 80, "Tim" : 95}

In [78]:
grades

{'Joel': 80, 'Tim': 95}

In [79]:
grades[0]

KeyError: 0

In [80]:
grades["Joel"]

80

In [81]:
grades["Alan"]

KeyError: 'Alan'

In [82]:
grades["Alan"] = 1000000000


In [83]:
grades["Alan"]

1000000000

In [84]:
try:

SyntaxError: unexpected EOF while parsing (<ipython-input-84-b998dae0d192>, line 1)

In [87]:
try:
    print(grades["Lindsay"])
except KeyError:
    grades["Lindsay"] = 100

In [88]:
grades

{'Joel': 80, 'Tim': 95, 'Alan': 1000000000, 'Lindsay': 100}

In [90]:
tweet = {"user" : "alan",
         "text" : "this is a meta tweet",
         "retweet_count" : 100,
         "hashtags" : ["#stuff", "compsci", "python"]}


In [91]:
tweet.keys()

dict_keys(['user', 'text', 'retweet_count', 'hashtags'])

In [92]:
tweet.values()

dict_values(['alan', 'this is a meta tweet', 100, ['#stuff', 'compsci', 'python']])

In [93]:
tweet.items()

dict_items([('user', 'alan'), ('text', 'this is a meta tweet'), ('retweet_count', 100), ('hashtags', ['#stuff', 'compsci', 'python'])])